#!/bin/zsh
# Verifies src/popup/index.html still satisfies every DOM dependency in src/popup/popup.js.
cd "$(dirname "$0")/.."
fail=0

echo "--- IDs required by src/popup/popup.js ---"
for id in checkin-time checkout1-target checkout1-status checkout1-countdown-wrap \
          fulltime-target fulltime-status fulltime-countdown-wrap today-progress \
          cycle-label refreshBtn login-alert alert-text cb-6-8-hours cb-requests \
          cb-below-6-hours below-8-hours-details no-attendance-details themeBtn \
          below-6-hours-details leave-used absent-count freshness cycle-balance history-strip optionsBtn worked-info tab-attendance tab-calendar view-attendance view-calendar calendar-grid calendar-label langBtn; do
  count=$(grep -c "id=\"$id\"" src/popup/index.html)
  if [[ $count -ne 1 ]]; then
    echo "  FAIL $id (found $count, expected 1)"
    fail=1
  fi
done
[[ $fail -eq 0 ]] && echo "  all required IDs present exactly once"

echo "--- CSS classes generated by src/popup/popup.js ---"
for cls in "\.cb-slot" "\.checked" "\.warning" "\.count-pill" "\.active" "\.alert" \
           "\.cb-slot\.over" "\.count-pill\.warn" "\.live-countdown" "\.time-active" "\.time-late" "\.time-completed" "\.spinning"; do
  if ! grep -q "$cls" src/popup/index.html; then
    echo "  FAIL no rule for ${cls//\\/}"
    fail=1
  fi
done
[[ $fail -eq 0 ]] && echo "  all generated classes styled"

echo "--- MV3 / CSP safety ---"
grep -qE '<script[^>]*>[^<]' src/popup/index.html && { echo "  FAIL inline <script> present"; fail=1; }
grep -qE ' on[a-z]+="' src/popup/index.html && { echo "  FAIL inline event handler present"; fail=1; }
remote=$(grep -oE 'https?://[^"'"'"' )]+' src/popup/index.html | grep -v 'w3.org' | sort -u)
echo "  remote URLs: ${remote:-none}"
grep -q "script type=\"module\" src=\"popup.js\"" src/popup/index.html || { echo "  FAIL popup.js not linked from its page"; fail=1; }
grep -q 'id="login-alert"[^>]*style="display: *none' src/popup/index.html || { echo "  FAIL login-alert must start hidden"; fail=1; }

echo "--- containers src/popup/popup.js overwrites must be empty ---"
node -e '
const fs = require("fs");
const html = fs.readFileSync("src/popup/index.html", "utf8");
let bad = 0;
for (const id of ["cb-6-8-hours", "cb-requests", "cb-below-6-hours"]) {
  const m = new RegExp(`id="${id}"[^>]*>([\\s\\S]*?)</div>`).exec(html);
  const inner = m ? m[1].replace(/<!--[\s\S]*?-->/g, "").trim() : "MISSING";
  if (inner !== "") { console.log(`  FAIL ${id} not empty: ${inner.slice(0,60)}`); bad = 1; }
}
if (!bad) console.log("  all three containers empty");
process.exit(bad);
' || fail=1

echo
[[ $fail -eq 0 ]] && echo "CONTRACT OK" || echo "CONTRACT VIOLATIONS FOUND"
exit $fail
